name: Test build

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: win
            runner: windows-latest
            targets: "nsis"
            arch: "--x64"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"

      - name: Install Node dependencies
        run: bun install --frozen-lockfile

      - name: Package GoofCord
        run: bunx electron-builder ${{ matrix.arch }} --${{ matrix.name }} ${{ matrix.targets }} --publish=never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-artifacts
          path: |
            dist/*.tar.xz
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.zip
            dist/*.exe
            dist/*.dmg
